const Team2023 = [
  {
    image: "https://drive.google.com/uc?id=1UzKu1WzlbwGF-HqLOOYWsHwpUOn__8e3&export=download",
    name: "Somu yadav",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/somu-yadav-32720a327/",
    gmail: "somuuuyadav@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451852/team/Team2023/Somu_yadav.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1k83tIC7TuE2jqwvVCRgomDBLOA7_V2wY&export=download",
    name: "Utkarsh Saxena",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/utkarsh-saxena-5a961b2b3?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
    gmail: "utkarshsaxena047@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451853/team/Team2023/Utkarsh_Saxena.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1r_bya-AT7GSN7uybrneyGSjUDYt4tRrb&export=download",
    name: "B.Sri harshitha",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/sriharshithab",
    gmail: "sriharshithab107@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451856/team/Team2023/B.Sri_harshitha.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1u2vrK5tF2XUC4Dq_UTDC8M3Ho8v7L2v0&export=download",
    name: "Aditi Bhushan",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/aditi-bhushan-53075736b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    gmail: "aditibhushan202@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451859/team/Team2023/Aditi_Bhushan.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1L20rpFYgvcM0Nq7ePH-cwUwAPPzM4Z56&export=download",
    name: "Ashish Maurya",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/ashish-p-maurya?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    gmail: "ashishmauryasvnit@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451861/team/Team2023/Ashish_Maurya.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1gCwD9eBCQ30evazE5IEPD9mGkT1ZewwK&export=download",
    name: "Niyal Patidar",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/niyalpatidar?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
    gmail: "niyalpatidar123@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451863/team/Team2023/Niyal_Patidar.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1zQrGx94hw68DNnJiGp8ZNU03hBlfxKYn&export=download",
    name: "Ayush Manth",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/ayush-manth-86688a286?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
    gmail: "manthayush2611@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451866/team/Team2023/Ayush_Manth.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1JHM5BQzazcNPf-vilatsL2zcSjDuwcrM&export=download",
    name: "Vijay Shrivas",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/vijay-s1",
    gmail: "i23cy025@chem.svnit.ac.in",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451869/team/Team2023/Vijay_Shrivas.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1yqyMz8ZmU-K9wbw0zSKRP6Zrb0BhCJWT&export=download",
    name: "Gadasanda Niharika",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/niharika-gadasanda-a5153930b",
    gmail: "niharikagadasanda@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451871/team/Team2023/Gadasanda_Niharika.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1ZSPFmkXTjaGE_9S81SnE_TeTIIMeM_Bn&export=download",
    name: "Ashish Kumar Shukla",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/ashishshukla07?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    gmail: "ashishshukla.jnt@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451874/team/Team2023/Ashish_Kumar_Shukla.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1tX0SfW5P3G3yVf-MnGl924F8VRkMcZaY&export=download",
    name: "PAWAR SAITEJA",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/pawarsaiteja",
    gmail: "pawarsaiteja1729@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451876/team/Team2023/PAWAR_SAITEJA.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1dq5K_ykNp_Ad_rxTq_sbQAEu_WMvLHNA&export=download",
    name: "Sudipta Bala",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/sudipta-bala-690988286",
    gmail: "mbala0709@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451879/team/Team2023/Sudipta_Bala.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1C0KQ1RCJs2YJ3mErNXVZHl82DllnDNwI&export=download",
    name: "Abhishek saini",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/abhishek-saini-b89033395?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    gmail: "abhisheksaini08620@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451881/team/Team2023/Abhishek_saini.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1W5yU_Y-D-sQemFLpWIpXb-vBs7bBGBR7&export=download",
    name: "Bolla Bhuvana",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/bhuvana-bolla-51b0a831a",
    gmail: "bollabhuvana5@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451883/team/Team2023/Bolla_Bhuvana.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1fX2uKqLC3Exr9NShMMkT_WP_TQITuCQL&export=download",
    name: "Shivansh Rastogi",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/shivansh-rastogi-a1004b301?trk=contact-info",
    gmail: "shivanshrastogi1000@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451888/team/Team2023/Shivansh_Rastogi.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1CjDcRdm4gG9E0TlUpciRztHtvi3gw4Td&export=download",
    name: "Anisha Patel",
    position: "Volunteer",
    linkedin: "www.linkedin.com/in/anisha1302",
    gmail: "anishapatel13022005@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451890/team/Team2023/Anisha_Patel.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=15Mk86SbHR5lRT49kqzY3ladCyr8282Se&export=download",
    name: "Anand Chaudhary",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/anand-chaudhary-5b029b343?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    gmail: "anandnitsurat@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451893/team/Team2023/Anand_Chaudhary.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1lOuN28-t0M2QGmuO9byl3MHzrYUBxuJD&export=download",
    name: "Sanidhya Mandliya",
    position: "Volunteer",
    linkedin: "http://linkedin.com/in/sanidhya-mandliya-2417ba3a2",
    gmail: "sanidhyamandliya1611@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451896/team/Team2023/Sanidhya_Mandliya.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=13l0uzqEYeLSrjlWCDq8gzvRfOYV5zRX5&export=download",
    name: "Abhishek Kumar",
    position: "Volunteer",
    linkedin: "www.linkedin.com/in/abhishek565",
    gmail: "abhishek5605raj@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451900/team/Team2023/Abhishek_Kumar.png",
  },
  {
    image: "https://drive.google.com/uc?id=1TpvLZqehjw9l8EN_leYXJ0t9yo9MyyV5&export=download",
    name: "Shubham Kumar",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/shubham-kumar-svnit-2ab430396",
    gmail: "kshubham7774@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451902/team/Team2023/Shubham_Kumar.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1DBH7dQ2fW0rKTh6UfbYbGu-uuSJU5yOF&export=download",
    name: "Rashmi",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/rashmi-bharti-svnit-7956bb394",
    gmail: "rashmibharti2408@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451905/team/Team2023/Rashmi.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1ANW-nrr4XUpaklSYkQ3XUtCTt2q0Nm-X&export=download",
    name: "Abhinav Upadhyay",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/abhinav-upadhyay08?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    gmail: "abhinavup1108@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451908/team/Team2023/Abhinav_Upadhyay.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1REiQfPd5aSzOFPcpXWJKsK9jxwL9X42s&export=download",
    name: "Priyansi",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/priyansi-s-697126346",
    gmail: "priyansis79@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451911/team/Team2023/Priyansi.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=10AvL564po4bvQQMCcN0hz_t1iKbYGC1R&export=download",
    name: "Pandey bhaveshkumar",
    position: "Volunteer",
    linkedin: "bhaveshpandey74@gmail.com",
    gmail: "pandeybhavesh999@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451913/team/Team2023/Pandey_bhaveshkumar.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1Wj6liECaByLYggAIgs5Wc5078A0_6VXu&export=download",
    name: "Hare Krishna Tiwari",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/harekrishnatiwari07/",
    gmail: "harekrishnat7@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451915/team/Team2023/Hare_Krishna_Tiwari.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1JEuga6bIEPCka_OZZerYuygnUFHw2LES&export=download",
    name: "Rohan Raj Singh",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/rohan-singh-266aa7359?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    gmail: "singhrohan6555@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451918/team/Team2023/Rohan_Raj_Singh.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1XHrukk-3XbCTARp7DsAQALOKfhOdTZEL&export=download",
    name: "Namrata Ramesh Patil",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/namrata-patil-220714282?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    gmail: "namratap369@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451921/team/Team2023/Namrata_Ramesh_Patil.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=189TnOBJATPA-eVUvsSXi4MGQknKJMrBD&export=download",
    name: "Moksh Chugh",
    position: "Volunteer",
    linkedin: "https://www.instagram.com/mokshhh_1908?igsh=Zm0zZmxidXhwbWNo&utm_source=qr",
    gmail: "mokshchugh301@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451923/team/Team2023/Moksh_Chugh.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1jH90WHu5ul-YYqjfgINtj5dlM0hMSfA1&export=download",
    name: "Tanish Makwana",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/tanish-makwana-svnit-84871a292?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    gmail: "tanishmakwana1992000@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451926/team/Team2023/Tanish_Makwana.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1XTeddb_XMiuG3up9BQEnWAYrNDYtWny7&export=download",
    name: "Abhinav Singh",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/abhinav-singh-505369306?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    gmail: "abhinavsingh47524753@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451928/team/Team2023/Abhinav_Singh.webp",
  },
  {
    image: "https://drive.google.com/uc?id=1yIOwmDjlrZ7L0zWCPG3esZ1aMCms3oot&export=download",
    name: "Prasanthi Kannuru",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/prasanthi-kannuru-0b8009285?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    gmail: "kannuruprasanthi@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451931/team/Team2023/Prasanthi_Kannuru.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1Kssbrr7uXUgeaPcvJSLbpL9ZXBUxkW-L&export=download",
    name: "SONALI RATHORE",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/sonali-rathore-735b13296?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    gmail: "sonalirathore1721@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451933/team/Team2023/SONALI_RATHORE.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=17xXZcZCI7foOATnh_4SSnWfCY3N1GJB5&export=download",
    name: "Aniket Kumar Bhandari",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/aniketkumarbhandari/",
    gmail: "aniketkumarbhandari@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451935/team/Team2023/Aniket_Kumar_Bhandari.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1Ktknerj2uwXkKafTkcnNpd-5lIx0u2-1&export=download",
    name: "Harsh Indorwala",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/harsh-indorwala-98b212375",
    gmail: "harsh.indorwala05@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451938/team/Team2023/Harsh_Indorwala.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1Y1ohfnvhQbLSFYU0ZI3nJ6NtsuqBMT8W&export=download",
    name: "Gupta Dharmendra",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/dharmendra-gupta-170092293?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    gmail: "dg614767@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451941/team/Team2023/Gupta_Dharmendra.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1ptqqEPuJTMr_-PI2yCGbHw9Fk7FfVujj&export=download",
    name: "Prathmesh Khode",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/prathmesh-khode-b22228330?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    gmail: "prathmeshkhode007@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451944/team/Team2023/Prathmesh_Khode.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1uLhWls_4cVwhujjT2B7e8VrYSxwkED1L&export=download",
    name: "Dhrumil Panchal",
    position: "Volunteer",
    linkedin: "www.linkedin.com/in/dhrumil-panchal-4b8411288",
    gmail: "dhrumil.techwork@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451949/team/Team2023/Dhrumil_Panchal.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1IT5ZphvxMBDAC1TgBfzmFbvdvibMIN7h&export=download",
    name: "Raghvendra Singh Solanki",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/raghvendra-singh-677560314?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    gmail: "raghavsholankii3011@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451951/team/Team2023/Raghvendra_Singh_Solanki.heic",
  },
  {
    image: "https://drive.google.com/uc?id=1eF35BN1LgmaKJLLcpBqDWGCsaxWSmFlB&export=download",
    name: "Swati Srivas",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/swati71?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    gmail: "swatishivprasad7704@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451954/team/Team2023/Swati_Srivas.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1MHi-VKveWUXYShXWtHv_TZBX7jKqe3-9&export=download",
    name: "Manya Pahwa",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/manya-pahwa-15434a357?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    gmail: "manyapahwa21@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451957/team/Team2023/Manya_Pahwa.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1tpS6EhHldUlz0X2lVUHiwimUVKJC74fo&export=download",
    name: "Arpita Gupta",
    position: "Volunteer",
    linkedin: "linkedin.com/in/arpita-gupta-369427321/",
    gmail: "arpitakumargupta888@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451959/team/Team2023/Arpita_Gupta.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=11PHsugrM2LJsFue5FBCC2OFvy1_NNLyY&export=download",
    name: "Renuka Choudhary",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/renuka-choudhary-b6058a28a?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    gmail: "renukachoudhary022@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451962/team/Team2023/Renuka_Choudhary.png",
  },
  {
    image: "https://drive.google.com/uc?id=1igTNzB77i4RdHyHOAHLuObR6GcLP8Nzk&export=download",
    name: "Vansh Shaileshbhai Patel",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/vanshpatel562005?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    gmail: "sk5028997@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451965/team/Team2023/Vansh_Shaileshbhai_Patel.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1sp5BRBGA-uHAZORmVOz2WyglIe2rRHRc&export=download",
    name: "Narendra Darji",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/narendra-darji-9849ba2bb?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    gmail: "darjinarendra1008@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451968/team/Team2023/Narendra_Darji.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1VoHfMpEiOSc1I6kyXFWoMHUKl1B6q5Jm&export=download",
    name: "Shashi Bhushan Kanishk",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/shashi-bhushan-kanishk-668ba2369?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    gmail: "kanishk.sb22@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451970/team/Team2023/Shashi_Bhushan_Kanishk.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1BS-deCpX_fuLncMOYjTVvluSnkY_nd3u&export=download",
    name: "Bhavya Purohit",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/bhavya-purohit-06b0982a7?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    gmail: "bhavyapurohit9@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451974/team/Team2023/Bhavya_Purohit.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=155qOxhjA9fh3BZrfkjAdowBYD_hF9Non&export=download",
    name: "B.Sri harshitha",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/sriharshithab",
    gmail: "sriharshithab107@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451856/team/Team2023/B.Sri_harshitha.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1SPFkdMpZmHxSS2_M9b9DzZwpFjAdnCeP&export=download",
    name: "Priyanshu Arya",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/priyanshu-arya-99305a299?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    gmail: "priyanshuarya284@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451980/team/Team2023/Priyanshu_Arya.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1YLqKDQ9mCBENyiTbBzkyerihxC4hY9Z8&export=download",
    name: "Koustubh Choudhary",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/koustubh-choudhary-79912a290?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    gmail: "choudharykoustubh710@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451984/team/Team2023/Koustubh_Choudhary.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1k8lq3F58JbdjQf9E58z4N0XQNdH2RD3U&export=download",
    name: "Ayush Singh",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/ayush-singh-819590353?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    gmail: "singhjiaayush1234@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451987/team/Team2023/Ayush_Singh.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=18MotUm0obqb5tJpoQJDksA9-N85T2Gwd&export=download",
    name: "Aryan Zala",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/aryan-zala-20150727a",
    gmail: "aryanzala2005@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451991/team/Team2023/Aryan_Zala.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1jqYRbXgInTSruEPRgcaRLQFMCRohD9ua&export=download",
    name: "Astha Mishra",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/astha-mishra-089166315",
    gmail: "astha28february@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451994/team/Team2023/Astha_Mishra.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1x1idIpwLX5ewHAMRmIbchftYgZgY1ytJ&export=download",
    name: "Palak yadav",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/palak-yadav-810919303?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    gmail: "palakyadavv5264@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770451997/team/Team2023/Palak_yadav.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1C5uXArLylYE9_fpT-BzFKx2BmrjQPf8i&export=download",
    name: "Abhishek Kumar",
    position: "Volunteer",
    linkedin: "www.linkedin.com/in/abhishek565",
    gmail: "abhishek5605raj@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770452000/team/Team2023/Abhishek_Kumar.png",
  },
  {
    image: "https://drive.google.com/uc?id=1mgTt0LOWHBZ6Sz8Rx3FbNtncs4UJJMmi&export=download",
    name: "Harsh Bhadani",
    position: "Volunteer",
    linkedin: "https://share.google/VA2WtCmd7T2xWzdAx",
    gmail: "harshkbhadani1906@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770452003/team/Team2023/Harsh_Bhadani.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1lrrHUmF6heaQ4pUnSoJETmPzgqEGZS5d&export=download",
    name: "Kajal Kumari",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/kajal-kumari-16a1483a9?trk=contact-info",
    gmail: "k6201109610@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770452006/team/Team2023/Kajal_Kumari.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1qgOXPqN8jIY5iJVDgwP2XhT2RSPczQDc&export=download",
    name: "Ritik sharma",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/ritik-sharma-54129028a/en/",
    gmail: "ritiksharmaddhs2005@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770452009/team/Team2023/Ritik_sharma.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1xTssgtn_k3mzQWt8Njs8Ihu9Dw5zvWxf&export=download",
    name: "Maheswar Samal",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/maheswar-samal-707b982b7?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    gmail: "maheswarsamal065@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770452013/team/Team2023/Maheswar_Samal.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1dVy6Y5LBctR7kpaCpkBAZDFtULURgg2A&export=download",
    name: "Anand sonage",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/anand-sonage-521a642b2?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    gmail: "anandsonage45@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770452015/team/Team2023/Anand_sonage.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1U5G7JKbqLV01FvUxM2xENetK-cNMkq7Z&export=download",
    name: "Mahaveer Regar",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/mahaveer-regar-646702380",
    gmail: "mahaveerregar738@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770452019/team/Team2023/Mahaveer_Regar.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1nhV8cwtp7OzRy8-5Hx2Favd4kammJlPs&export=download",
    name: "Budda Pallavi",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/budda-pallavi-418aa228b",
    gmail: "buddapallavi057@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770452021/team/Team2023/Budda_Pallavi.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1PDMxDD8mzeI2nLXvU7xjp206u9aqzCLf&export=download",
    name: "Priti Sand",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/priti-sand?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    gmail: "pritisand31@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770452024/team/Team2023/Priti_Sand.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1KoK860-y71v_zd5ofaLFOVtBrcntegXC&export=download",
    name: "Harsh Sarwate",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/harsh-sarwate",
    gmail: "harshsarwate@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770452027/team/Team2023/Harsh_Sarwate.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1nMq14NMrZT51FlNEieo8f04vbauAFkIK&export=download",
    name: "Budde Varshini",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/varshini-budde-613976306/",
    gmail: "varshinibudde11@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770452031/team/Team2023/Budde_Varshini.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1e2MDSR9mXDVUMTUvibk8A17DkE-IcZ8G&export=download",
    name: "Pradnya Pagare",
    position: "Volunteer",
    linkedin: "pradnyapagare2005@gmail.com",
    gmail: "pradnyapagare2005@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770452036/team/Team2023/Pradnya_Pagare.jpg",
  },
  {
    image: "https://drive.google.com/uc?id=1dHw-XqShjqqMHY10LOI0004s7isaQn0_&export=download",
    name: "Kummari Samyuktha",
    position: "Volunteer",
    linkedin: "https://www.linkedin.com/in/samyuktha-kummari-a38a64210?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    gmail: "abhisamyuktha788@gmail.com",
    firebase: "https://res.cloudinary.com/dh0zqs0nw/image/upload/v1770452040/team/Team2023/Kummari_Samyuktha.jpg",
  },
];
