// This file re-exports date-fns functions in the format expected by MUI X Date Pickers
import addDaysDefault from "date-fns/addDays";
import addMonthsDefault from "date-fns/addMonths";
import addSecondsDefault from "date-fns/addSeconds";
import addYearsDefault from "date-fns/addYears";
import differenceInDaysDefault from "date-fns/differenceInDays";
import differenceInMonthsDefault from "date-fns/differenceInMonths";
import differenceInYearsDefault from "date-fns/differenceInYears";
import eachDayOfIntervalDefault from "date-fns/eachDayOfInterval";
import endOfDayDefault from "date-fns/endOfDay";
import endOfMonthDefault from "date-fns/endOfMonth";
import endOfWeekDefault from "date-fns/endOfWeek";
import endOfYearDefault from "date-fns/endOfYear";
import {
	default as formatDefault,
	default as formatWithOptionsDefault,
} from "date-fns/format";
import formatDistanceDefault from "date-fns/formatDistance";
import formatISODefault from "date-fns/formatISO";
import getDateDefault from "date-fns/getDate";
import getDaysInMonthDefault from "date-fns/getDaysInMonth";
import getHoursDefault from "date-fns/getHours";
import getMinutesDefault from "date-fns/getMinutes";
import getMonthDefault from "date-fns/getMonth";
import getSecondsDefault from "date-fns/getSeconds";
import getWeekDefault from "date-fns/getWeek";
import getYearDefault from "date-fns/getYear";
import isAfterDefault from "date-fns/isAfter";
import isBeforeDefault from "date-fns/isBefore";
import isEqualDefault from "date-fns/isEqual";
import isSameDayDefault from "date-fns/isSameDay";
import isSameHourDefault from "date-fns/isSameHour";
import isSameMonthDefault from "date-fns/isSameMonth";
import isSameYearDefault from "date-fns/isSameYear";
import isValidDefault from "date-fns/isValid";
import isWithinIntervalDefault from "date-fns/isWithinInterval";
import parseDefault from "date-fns/parse";
import parseISODefault from "date-fns/parseISO";
import setDateDefault from "date-fns/setDate";
import setHoursDefault from "date-fns/setHours";
import setMinutesDefault from "date-fns/setMinutes";
import setMonthDefault from "date-fns/setMonth";
import setSecondsDefault from "date-fns/setSeconds";
import setYearDefault from "date-fns/setYear";
import startOfDayDefault from "date-fns/startOfDay";
import startOfMonthDefault from "date-fns/startOfMonth";
import startOfWeekDefault from "date-fns/startOfWeek";
import startOfYearDefault from "date-fns/startOfYear";

// Re-export as named exports for compatibility with MUI
export const addDays = addDaysDefault;
export const addSeconds = addSecondsDefault;
export const addMonths = addMonthsDefault;
export const addYears = addYearsDefault;
export const differenceInDays = differenceInDaysDefault;
export const differenceInMonths = differenceInMonthsDefault;
export const differenceInYears = differenceInYearsDefault;
export const eachDayOfInterval = eachDayOfIntervalDefault;
export const endOfDay = endOfDayDefault;
export const endOfMonth = endOfMonthDefault;
export const endOfWeek = endOfWeekDefault;
export const endOfYear = endOfYearDefault;
export const format = formatDefault;
export const formatWithOptions = formatWithOptionsDefault;
export const getDate = getDateDefault;
export const getDaysInMonth = getDaysInMonthDefault;
export const getHours = getHoursDefault;
export const getMinutes = getMinutesDefault;
export const getMonth = getMonthDefault;
export const getSeconds = getSecondsDefault;
export const getWeek = getWeekDefault;
export const getYear = getYearDefault;
export const isAfter = isAfterDefault;
export const isBefore = isBeforeDefault;
export const isEqual = isEqualDefault;
export const isSameDay = isSameDayDefault;
export const isSameHour = isSameHourDefault;
export const isSameMonth = isSameMonthDefault;
export const isSameYear = isSameYearDefault;
export const isValid = isValidDefault;
export const parse = parseDefault;
export const parseISO = parseISODefault;
export const setDate = setDateDefault;
export const setHours = setHoursDefault;
export const setMinutes = setMinutesDefault;
export const setMonth = setMonthDefault;
export const setSeconds = setSecondsDefault;
export const setYear = setYearDefault;
export const startOfDay = startOfDayDefault;
export const startOfMonth = startOfMonthDefault;
export const startOfWeek = startOfWeekDefault;
export const startOfYear = startOfYearDefault;
export const formatDistance = formatDistanceDefault;
export const formatISO = formatISODefault;
export const isWithinInterval = isWithinIntervalDefault;
